#!/usr/bin/env sh
#

_path() {
  # prepend $1 to the PATH if it's not already there

  dir="$1"
  if [ -d "$dir" ] ; then
    echo "$PATH" | grep -q "$dir" || export PATH="$dir:${PATH}"
  else
    echo "$0: FATAL: directory not found: $dir"
    return 1
  fi
}

# Make sure we have ~/bin and /usr/local/bin
_path /usr/local/bin || return
_path "$HOME"/bin || return
unset _path

# Make sure we have `path`
if ! command -v path >/dev/null 2>&1 ; then echo "Missing dependency: path" 1>&2 ; return 1 ; fi

#
# prepends
#

# homebrew curl

# If you need to have curl first in your PATH run:
#   echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile
# For compilers to find curl you may need to set:
#   export LDFLAGS="-L/usr/local/opt/curl/lib"
#   export CPPFLAGS="-I/usr/local/opt/curl/include"
#
# For pkg-config to find curl you may need to set:
#   export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
hb_curl_dir=/usr/local/opt/curl/bin

if [ -x "$hb_curl_dir" ] ; then
  eval "$(~/bin/path --replace --prepend "$hb_curl_dir")" || return
fi

if [ -d /usr/local/Cellar ] ; then
  eval "$(~/bin/path --replace --prepend /usr/local/Cellar)" || return
fi

if [ -d "$HOME"/.homebrew/bin ] ; then
  eval "$(~/bin/path --prepend "$HOME"/.homebrew/bin)" || return
fi

if [ -d "$HOME"/.local/bin ] ; then
  eval "$(~/bin/path --prepend "$HOME"/.local/bin)" || return
fi

eval "$(~/bin/path --replace --prepend "$HOME"/bin)" || return


#
# appends
#

# https://docs.python.org/3/library/site.html
if command -v python3 >/dev/null 2>&1 ; then
  py3base="$(python3 -m site --user-base)"/bin
  eval "$(~/bin/path --append "$py3base")" || return
fi

if command -v python2 >/dev/null 2>&1 ; then
  py2base="$(python2 -m site --user-base)"/bin
  eval "$(~/bin/path --append "$py2base")" || return
fi

# https://guides.rubygems.org/faqs/#user-install
if command -v ruby >/dev/null 2>&1 ; then
  rubygembase="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin" || return
  eval "$(~/bin/path --append "$rubygembase")" || return

  if [ -d "$HOME"/.rvm/bin ] ; then
    eval "$(~/bin/path --append "$HOME"/.rvm/bin)" || return
  fi
fi

if command -v cargo >/dev/null 2>&1 ; then
  eval "$(~/bin/path --append ~/.cargo/bin)" || return
fi

if command -v go >/dev/null 2>&1 ; then
  eval "$(~/bin/path --append ~/go/bin)" || return
fi

if command -v pipx >/dev/null 2>&1 ; then
  eval "$(~/bin/path --append "$HOME/.local/bin")" || return
fi
