#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2019 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

#   A colon-separated list of patterns defining the set of file names to be
#   ignored by pathname expansion. If a file name matched by a pathname
#   expansion pattern also  matches one of the patterns in # GLOBIGNORE, it is
#   removed from the list of matches.
# This lets you work around the infamous "I want to match all of my dot files, but not . or .." problem:
export GLOBIGNORE=.:..

# EOF
