#!/usr/bin/env bash

source_file() {
  local file
  file="$1"

  if [[ -f "$file" ]] ; then
    # shellcheck disable=SC1090
    source "$file"
  fi
}

# macos
source_file '/usr/local/etc/bash_completion'

# archlinux
source_file '/usr/share/bash-completion/bash_completion'
