#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

source_file() {
  local file
  file="$1"

  if [[ -f "$file" ]] ; then
    # shellcheck disable=SC1090
    source "$file"
  fi
}

# macos
source_file '/usr/local/etc/bash_completion'

# archlinux
source_file '/usr/share/bash-completion/bash_completion'

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
