#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

_path() {
  dir="$1"
  if [ -d "$dir" ] ; then
    echo "$PATH" | grep -q "$dir" || export PATH="$dir:${PATH}"
  else
    echo "$0: FATAL: directory not found: $dir"
    return 1
  fi
}

# Make sure we have ~/bin and /usr/local/bin
_path /usr/local/bin || return 1
_path "$HOME"/bin || return 1

# Make sure we have `path`
if ! command -v path >/dev/null 2>&1 ; then echo "Missing dependency: path" 1>&2 ; return 1 ; fi

#
# prepends
#

[ -d /usr/local/Cellar ] &&     eval "$(~/bin/path --replace --prepend /usr/local/Cellar)"
[ -d "$HOME"/.homebrew/bin ] && eval "$(~/bin/path --prepend "$HOME"/.homebrew/bin)"

eval "$(~/bin/path --prepend "$HOME"/bin --replace)"

#
# appends
#

# https://docs.python.org/3/library/site.html
if ! command -v python3 >/dev/null 2>&1 ; then
  py3base="$(python3 -m site --user-base)"/bin
  eval "$(~/bin/path --append "$py3base")"
fi

if ! command -v python2 >/dev/null 2>&1 ; then
  py2base="$(python2 -m site --user-base)"/bin
  eval "$(~/bin/path --append "$py2base")"
fi

# https://guides.rubygems.org/faqs/#user-install
if ! command -v ruby >/dev/null 2>&1 ; then
  rubygembase="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"
  eval "$(~/bin/path "$rubygembase")"

  [ -d "$HOME"/.rvm/bin ] && eval "$(~/bin/path --append "$HOME"/.rvm/bin)"
fi

# EOF
