#!/usr/bin/env bash
#
# © Copyright 2019 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

# Overrides inputrc location from the default of ~/.inputrc
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}"/inputrc

#   A colon-separated list of patterns defining the set of file names to be
#   ignored by pathname expansion. If a file name matched by a pathname
#   expansion pattern also  matches one of the patterns in # GLOBIGNORE, it is
#   removed from the list of matches.
# This lets you work around the infamous "I want to match all of my dot files, but not . or .." problem:
export GLOBIGNORE=.:..

  # append to the history file, don't overwrite it
shopt -s histappend
  # don't put duplicate lines in the history. See bash(1) for more options
HISTCONTROL=ignoreboth
  # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=80
HISTFILESIZE=50
  # Ignore some controlling instructions
  # HISTIGNORE is a colon-delimited list of patterns which should be excluded.
  # The '&' is a special pattern which suppresses duplicate entries.
export HISTIGNORE=$'[ \t]*:&:[fb]g:fc:exit:.:whereami:ranger*:asdf:aoeu:fuck:hist*'
export HISTIGNORE="$HISTIGNORE"':clear'

# UMASK {{{3
  # /etc/profile sets 022, removing write perms to group + others.
  # Set a more restrictive umask: i.e. no exec perms for others:
# umask 027
  # Paranoid: neither group nor others have any perms:
# umask 0077
# 3}}}

# EOF
