#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

append2path() {
  printf "%s:%s" "$1" "$PATH"
}

[ -d "$HOME"/bin ] && newpath="$(append2path "$HOME"/bin)"
export PATH="$newpath"

[ -d "$HOME"/.homebrew/bin ] && newpath="$(append2path "$HOME"/.homebrew/bin)"
export PATH="$newpath"

# https://docs.python.org/3/library/site.html
py3base="$(python3 -m site --user-base)"/bin
newpath="$(append2path "$py3base")"
export PATH="$newpath"

py2base="$(python2 -m site --user-base)"/bin
newpath="$(append2path "$py2base")"
export PATH="$newpath"

[ -d "$HOME"/.rvm/bin ] && newpath="$(append2path "$HOME"/.rvm/bin)"
export PATH="$newpath"

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
