#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  :
  # UMASK {{{3
    # /etc/profile sets 022, removing write perms to group + others.
    # Set a more restrictive umask: i.e. no exec perms for others:
  # umask 027
    # Paranoid: neither group nor others have any perms:
  # umask 0077
  # }}}
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
