#!/usr/bin/env sh
#

_shellenv_path_prepend "/opt/homebrew/opt/grep/libexec/gnubin"
_shellenv_path_prepend "/opt/homebrew/opt/gnu-sed/libexec/gnubin"
_shellenv_path_prepend "/opt/homebrew/opt/gnu-tar/libexec/gnubin"
_shellenv_path_prepend "/opt/homebrew/opt/gnu-which/libexec/gnubin"
_shellenv_path_prepend "/opt/homebrew/opt/findutils/libexec/gnubin"
