#!/usr/bin/env sh
#

# PS1: Prompt
  # unicode
export PROMPT_SYMBOL="$"
export PROMPT_SYNCED_SYMBOL=""
export PROMPT_DIRTY_SYNCED_SYMBOL="⬦"
export PROMPT_DIRTY_SYNCED_SYMBOL="✳"
export PROMPT_UNPUSHED_SYMBOL="↑"
export PROMPT_DIRTY_UNPUSHED_SYMBOL="⇡"
export PROMPT_UNPULLED_SYMBOL="↓"
export PROMPT_DIRTY_UNPULLED_SYMBOL="⇣"
export PROMPT_UNPUSHED_UNPULLED_SYMBOL="${PROMPT_UNPUSHED_SYMBOL}${PROMPT_UNPULLED_SYMBOL}"
export PROMPT_DIRTY_UNPUSHED_UNPULLED_SYMBOL="${PROMPT_DIRTY_UNPUSHED_SYMBOL}${PROMPT_DIRTY_UNPULLED_SYMBOL}"
export PROMPT_STOPPED_JOBS_SYMBOL="⯃"
export PROMPT_STOPPED_JOBS_SYMBOL="➤"

# emoji
#   TODO: we need to check that the terminal supports this before setting it
# export PROMPT_SYMBOL=""
# export PROMPT_SYNCED_SYMBOL=""
# export PROMPT_DIRTY_SYNCED_SYMBOL=""
# export PROMPT_UNPUSHED_SYMBOL="⤴️"
# export PROMPT_UNPUSHED_SYMBOL="⬆️"
# export PROMPT_DIRTY_UNPUSHED_SYMBOL=""
# export PROMPT_UNPULLED_SYMBOL="⤵️"
# export PROMPT_UNPULLED_SYMBOL="⬇️"
# export PROMPT_DIRTY_UNPULLED_SYMBOL=""
# export PROMPT_UNPUSHED_UNPULLED_SYMBOL="${PROMPT_UNPUSHED_SYMBOL}${PROMPT_UNPULLED_SYMBOL}"
# export PROMPT_DIRTY_UNPUSHED_UNPULLED_SYMBOL="${PROMPT_DIRTY_UNPUSHED_SYMBOL}${PROMPT_DIRTY_UNPULLED_SYMBOL}"
# export PROMPT_STOPPED_JOBS_SYMBOL="🛑"

if [ "$(id -u)" = 0 ] && type tput 1>/dev/null 2>/dev/null ; then
  # If we are root, try to make that hard to miss.
  # And de-emphasize git status (we don't work as root)
  PROMPT_USER_COLOR="$(tput bold)$(tput setab 196)$(tput setaf 0)"
  export PROMPT_USER_COLOR
  PROMPT_GIT_STATUS_COLOR="$(tput setaf 7)"
  export PROMPT_GIT_STATUS_COLOR
elif groups "$USER" | grep -qP '(\bwheel\b|\bsysop\b)'; then
  # If we are wheel, try to make that hard to miss.
  # And de-emphasize git status (we don't work as superuser)
  PROMPT_USER_COLOR="$(tput bold)$(tput setab 11)$(tput setaf 0)"
  export PROMPT_USER_COLOR
  PROMPT_GIT_STATUS_COLOR="$(tput setaf 7)"
  export PROMPT_GIT_STATUS_COLOR
elif groups "$USER" | grep -qP 'sudo(er(s)?)?'; then
  # If we are in sudoers,
  # Use defaults - do nothing
:
else
  # If we are not root, wheel, nor a sudoer,
  # Use unprivileged colorscheme
  PROMPT_USER_COLOR="$(tput setaf 2)"
  export PROMPT_USER_COLOR
fi
