#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

  # read in dircolors
if [[ -e "$HOME"/.bash_colors ]] ; then
  eval "$(gdircolors -b "$HOME"/.bash_colors || return $?)"
else
  eval "$(gdircolors -b || return $?)"
fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
