#!/usr/bin/env bash
#

# PS1: Prompt
if [[ -f "$HOME"/.bash_prompt ]]; then
  if [[ "$UID" == 0 ]] && type tput &> /dev/null; then
    # If we are root, try to make that hard to miss.
    # And de-emphasize git status (we don't work as root)
    PROMPT_USER_COLOR="$(tput bold)$(tput setab 196)$(tput setaf 0)"
    export PROMPT_USER_COLOR
    PROMPT_GIT_STATUS_COLOR="$(tput setaf 7)"
    export PROMPT_GIT_STATUS_COLOR
  elif groups "$USER" | grep -qP '(\bwheel\b|\bsysop\b)'; then
    # If we are wheel, try to make that hard to miss.
    # And de-emphasize git status (we don't work as superuser)
    PROMPT_USER_COLOR="$(tput bold)$(tput setab 11)$(tput setaf 0)"
    export PROMPT_USER_COLOR
    PROMPT_GIT_STATUS_COLOR="$(tput setaf 7)"
    export PROMPT_GIT_STATUS_COLOR
  elif groups "$USER" | grep -qP 'sudo(er(s)?)?'; then
    # If we are in sudoers,
    # Use defaults - do nothing
  :
  else
    # If we are not root, wheel, nor a sudoer,
    # Use unprivileged colorscheme
    PROMPT_USER_COLOR="$(tput setaf 2)"
    export PROMPT_USER_COLOR
  fi
  # shellcheck disable=SC1090
  source "$HOME"/.bash_prompt
fi

# PS2: Continuation prompt
# Default: '> '
export PS2="... "
# PS3: Option select prompt
# Default: '#?'
export PS3='#?'
# PS4: Script debug mode prefix
# Default: '+'
export PS4='+ ${FUNCNAME[0]:+${FUNCNAME[0]}():}line ${LINENO}: '

# EOF
