#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.

if ! command -v lynx >/dev/null 2>&1 ; then
    # Where to find the config
  export LYNX_CFG="$XDG_CONFIG_HOME/lynx/config"
    # Where to save downloaded files
  if [ -d "$HOME/incoming/" ] ; then
    export LYNX_SAVE_SPACE="$HOME/incoming"
  elif [ -d "$TMP" ] ; then
    export LYNX_SAVE_SPACE="$TMP"
  elif [ -d "/tmp/" ] ; then
    export LYNX_SAVE_SPACE="/tmp/"
  else
    export LYNX_SAVE_SPACE="$HOME"
  fi

# these settings don't just affect lynx, unfortunately.
  export WWW_HOME="https://duckduckgo.com/"
# export http_proxy="http://localhost:9050/" # http_proxy causes ALL http requests to be filtered through tor. :(
# export ftp_proxy="http://localhost:9050/"
# export gopher_proxy="http://localhost:9050/"
fi

# EOF
