#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if command -v vim >/dev/null 2>&1 ; then export EDITOR="vim" && export VISUAL="vim"; fi
if command -v gvim >/dev/null 2>&1 ; then export VISUAL="gvim"; fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
