#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.

if ! command -v adb >/dev/null 2>&1 ; then
    # Print debug information. A comma separated list of the following values 1 or
    # all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  export ADB_TRACE=""
    # The serial number to connect to. -s takes priority over this if given.
# export ANDROID_SERIAL=""
    # When used with the logcat option, only these debug tags are printed.
# export ANDROID_LOG_TAGS=
fi

# EOF
