#!/usr/bin/env sh
#

if command -v lynx >/dev/null 2>&1 ; then
    # Where to find the config
  export LYNX_CFG="$XDG_CONFIG_HOME/lynx/config"
    # Where to save downloaded files
  if [ -d "$HOME/incoming/" ] ; then
    export LYNX_SAVE_SPACE="$HOME/incoming"
  elif [ -d "$TMP" ] ; then
    export LYNX_SAVE_SPACE="$TMP"
  elif [ -d "/tmp/" ] ; then
    export LYNX_SAVE_SPACE="/tmp/"
  else
    export LYNX_SAVE_SPACE="$HOME"
  fi

# these settings don't just affect lynx, unfortunately.
  export WWW_HOME="https://duckduckgo.com/"
# export http_proxy="http://localhost:9050/" # http_proxy causes ALL http requests to be filtered through tor. :(
# export ftp_proxy="http://localhost:9050/"
# export gopher_proxy="http://localhost:9050/"
fi

# EOF
