#!/usr/bin/env bash
#

  # make a backup list of installed packages
packagebackup() {
  comm -23 <(pacman -Qeq|sort) <(pacman -Qmq|sort)
}

dirpath() {
  # print the PATH with each directory on a newline
  IFS=: read -ra paths <<< "$PATH"
  printf '%s\n' "${paths[@]}"
}

# EOF
