#!/usr/bin/env sh
#

  # cleanly become another user
alias become='sudo su --login'

  # sudo a command, preserving the current environment
alias sudoe='sudo -E'

  # package manager
if command -v pacman >/dev/null 2>&1 ; then
  alias pacman='\pacman --color=always'
  alias ya='pacman'
  alias yaq='ya -Q'
  alias yas='ya -S'
  alias yass='ya -Ss'
  alias yars='ya -Rs'
fi

if command -v yay >/dev/null 2>&1 ; then
  alias ya='\yay --color=always'
  alias yaq='ya -Q'
  alias yas='ya -S'
  alias yass='ya -Ss'
  alias yars='ya -Rs'
fi


if command -v brew >/dev/null 2>&1 ; then
  alias ya='\brew'
  alias yaq='ya info'
  alias yas='ya install'
  alias yass='ya search'
  alias yars='ya uninstall'
fi

  # watch incoming network connections
alias netmonitor='\sudo watch -n 3 lsof -i'

if command -v youtube-dl >/dev/null 2>&1 ; then
    # don't mark videos watched
  alias youtube-dl='youtube-dl --no-mark-watched'
    # youtube-dl with lots of metadata
  alias youget='youtube-dl --output "%(title)s-%(id)s.%(ext)s" -c -w --write-info-json --write-description --'
    # Convert Youtube videos to MP3
  alias youtube-dla='youtube-dl --output "%(title)s-%(id)s.%(ext)s" --extract-audio --audio-format mp3 --'
fi

  # save a dnuos list with stats starting from pwd
command -v dnuos >/dev/null 2>&1 && alias oidua='\dnuos --file=list -D -S -t .'

  # tmux is the new screen
command -v tmux >/dev/null 2>&1 && [ -f "$XDG_CONFIG_HOME"/tmux/tmux.conf ] && alias tmux='tmux -f ~/.config/tmux/tmux.conf'

  # mpd
if command -v ncmpcpp >/dev/null 2>&1 ; then
    alias mplay='ncmpcpp play'
    alias mpause='ncmpcpp pause'
    alias mtoggle='ncmpcpp toggle'
    alias mstop='ncmpcpp stop'
    alias mnext='ncmpcpp next'
    alias mprev='ncmpcpp prev'
    alias mvolume='ncmpcpp volume'
fi

  # vlc is best from a terminal :V
command -v vlc >/dev/null 2>&1 && alias ncvlc='vlc -I ncurses'

  # watch incoming network connections
alias netmonitor='watch -n 3 lsof -i'

    # ls / exa
if command -v exa >/dev/null 2>&1 ; then
  # exa aliases go here
  alias exa='exa --color=always --icons'
  alias l='exa --group-directories-first'
  alias ll='exa --long --header --git --links --group-directories-first --color-scale --time-style=long-iso'
  alias la='ll --all'
  alias lr='ll --tree --level 2'
else
  alias l='ls --format=across --group-directories-first'
  alias ll='ls --group-directories-first --human-readable --dereference -l --indicator-style=slash --time-style=+"%Y-%m-%d"'
  alias la='ll --dereference-command-line --all'
  alias lr='ll recursive'
fi

alias lla='la'
alias lll='ll --color=always | pager'
alias llla='lla --color=always | pager'

    # safety valve
alias mv='mv --verbose --interactive'
alias cp='cp --verbose --interactive'
alias rm='rm --verbose -I'
alias chown='chown --changes --preserve-root'
alias chmod='chmod --changes --preserve-root'
alias chgrp='chgrp --changes --preserve-root'

  # Make directory including intermediate directories
alias mkdir='mkdir --verbose --parents'

    # Gocbi ekrpat co nct. lnafcbi a lpajycjan hrt. rb frgpo.nu
alias asdf='setxkbmap dvorak'

    # colordiff is the new diff
command -v colordiff >/dev/null 2>&1 && alias diff='colordiff'

    # use grc to add color command support
if command -v grc >/dev/null 2>&1 ; then
    alias hilite='\grc --stdout --stderr --colour=on'
    alias configure='hilite ./configure'
    alias make='hilite make'
    alias gcc='hilite gcc'
    alias g++='hilite g++'
    alias as='hilite as'
    alias gas='hilite gas'
    alias ld='hilite ld'
    alias netstat='hilite netstat'
    alias ping='hilite ping'
    alias ifconfig='hilite ifconfig'
    alias traceroute='hilite /usr/sbin/traceroute'
fi

    # use colors in ip
if command -v ip >/dev/null 2>&1 ; then
  alias ip='ip -d -c'
fi

    # disk usage in plain english
alias disk='df --local --print-type --si'
alias df='df --si'

if command -v rsync >/dev/null 2>&1 ; then
    # rsync is the new (s)cp
  alias rp='\rsync --archive --copy-links --inplace --verbose --stats --progress'
    # rsync is the new mv
  alias rv='\rsync --archive --copy-links --inplace --verbose --stats --progress --remove-source-files'
fi

    # grep can be pretty :*
if command -v grep >/dev/null 2>&1 ; then
  alias crep='\grep --color=always'
  alias acrep='\agrep --color=always'
  alias fcrep='\fgrep --color=always'
  alias ecrep='\egrep --color=always'
  alias search='\grep --color=never --with-filename --binary-files=text --directories=recurse --files-with-matches --line-number'
fi

    # mount
command -v mount >/dev/null 2>&1 && command -v column >/dev/null 2>&1 && alias mounts='\mount | \column -t | pager'
command -v mountpoint >/dev/null 2>&1 && alias mp='mountpoint'

    # private shredder
command -v shred >/dev/null 2>&1 && alias shred=' shred --verbose'

  # always make secure passwords
command -v apg >/dev/null 2>&1 && alias apg=' apg -a 1 -n 1 -m 16 -x 32'

  # weechat is dumb
command -v weechat >/dev/null 2>&1 && [ -n "$XDG_CONFIG_HOME" ] && alias weechat='weechat --dir "$XDG_CONFIG_HOME"/weechat/'

  # dosbox coercion to use XDG standard
command -v dosbox >/dev/null 2>&1 && [ -f "$XDG_CONFIG_HOME/dosbox/dosbox.conf" ] && alias dosbox='dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf'

  # getmail coercion to use XDG standard
getmaildir="$XDG_CONFIG_HOME/getmail"
if command -v getmail >/dev/null 2>&1 ; then
  if [ -d  "$getmaildir" ]; then
    # shellcheck disable=SC2139
    alias getmail='getmail --getmaildir='"$getmaildir"
  fi
fi

  # abook coercion to use XDG standard
if command -v abook >/dev/null 2>&1 ; then
  datafile="$HOME/docs/addressbook"
  if [ -r "$datafile" ]; then
    alias abook='abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile $datafile'
  else
    alias abook='abook --config "$XDG_CONFIG_HOME"/abook/abookrc'
  fi
fi

  # copy-paste to clipboard
if command -v xclip >/dev/null 2>&1 ; then
  alias clip="xclip -selection clipboard"
fi

  # pudb
if command -v pudb3 >/dev/null 2>&1 ; then
  alias pudb='pudb3'
fi

  # vim monkey stuff
alias ZQ='exit'
alias ZZ='exit'

  # netctl-auto
  # if netctl-auto is running, then manually starting a wireless network with
  # 'netctl' will always fail. therefore, we alias 'netctl' to 'netctl-auto'
if command -v netctl-auto >/dev/null 2>&1 ; then
  if systemctl status netctl-auto@wlp7s0 >/dev/null 2>&1 ; then
    alias netctl='netctl-auto'
  fi
fi

  # pypi2pkgbuild
if command -v pypi2pkgbuild.py >/dev/null 2>&1 ; then
  alias pypi2pkg='PKGEXT=.pkg.tar pypi2pkgbuild.py -g cython -b /tmp/pypi2pkgbuild/ -f'
fi

  # sxiv
if command -v sxiv >/dev/null 2>&1 ; then
  alias sxiv='sxiv -a -p'
fi

  # pwstore
if command -v pwstore >/dev/null 2>&1 ; then
  alias pw='pwstore'
fi

  # pylint
  # always alias this since maybe it's only in the venv
alias pylint='pylint --rcfile "$XDG_CONFIG_HOME"/pylint/config'

  # ptpython
  # always alias this since maybe it's only in the venv
alias ptpython='ptpython --config-dir "$XDG_CONFIG_HOME"/ptpython'
alias ptpython3='ptpython3 --config-dir "$XDG_CONFIG_HOME"/ptpython'

# EOF
