#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
    # make a backup list of installed packages
  packagebackup() {
    comm -23 <(pacman -Qeq|sort) <(pacman -Qmq|sort)
  }

    # sort installed packages by size and print a list to stdout
  packagesize() {
    paste <(pacman -Q | awk '{ print $1; }' | xargs pacman -Qi | \
    grep 'Size' | awk '{ print $4$5; }') \
    <(pacman -Q | awk '{print $1;}') | sort -n | column -t | \
    'sed' -r 's@\.[0-9]{2}KiB@MiB@'
  }

}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
