#!/usr/bin/env sh
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

command_exists() {
  command="$1"

  # shellcheck disable=SC2069
  if command -v "$command" >/dev/null 2>&1 ; then
    return 0
  else
    return 1
  fi
  return 1
}

alias screensaver='/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
alias lock='pmset displaysleepnow'

if command_exists gtimeout ; then
  alias timeout='gtimeout'
fi
if command_exists gmv ; then
  alias mv='gmv -iv'
fi
if command_exists gcp ; then
  alias cp='gcp -iv'
fi
if command_exists grm ; then
  alias rm='grm -Iv'
fi
if command_exists ggrep ; then
  alias grep='ggrep'
fi
if command_exists gchmod ; then
  alias chmod='gchmod -c --preserve-root'
fi
if command_exists gchown ; then
  alias chown='gchown -c --preserve-root'
fi
if command_exists gchgrp ; then
  alias chgrp='gchgrp -c --preserve-root'
fi
if command_exists gstat ; then
  alias stat='gstat'
fi
if command_exists gdate ; then
  alias date='gdate'
fi
if command_exists gprintf ; then
  alias printf='gprintf'
fi
if command_exists gmktemp ; then
  alias mktemp='gmktemp'
fi
if command_exists gtac ; then
  alias tac='gtac'
fi
if command_exists gcat ; then
  alias cat='gcat'
fi
if command_exists gdf ; then
  alias df='gdf'
fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
