#!/usr/bin/env sh
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

command_exists() {
  command="$1"

  # shellcheck disable=SC2069
  if command -v "$command" >/dev/null 2>&1 ; then
    return 0
  else
    return 1
  fi
  return 1
}

alias screensaver='/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
alias lock='pmset displaysleepnow'

if command_exists gtimeout ; then
  alias timeout='gtimeout'
fi
if command_exists gmv ; then
  alias mv='gmv'
fi
if command_exists gcp ; then
  alias cp='gcp'
fi
if command_exists grm ; then
  alias rm='grm'
fi
if command_exists ggrep ; then
  alias grep='ggrep'
fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
