#!/usr/bin/env zsh
# zsh 5.3 (x86_64-apple-darwin17.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if command -v direnv &>/dev/null; then
    eval "$(direnv hook bash)"
fi

# vim: filetype=zsh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
