#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if command -v gpg >/dev/null 2>&1 ; then
    # Remember the current tty (so we don't bleed permissions?)
  GPG_TTY="$(tty)"
  export GPG_TTY
  if [ -d "$XDG_CONFIG_HOME/gnupg/" ] ; then
    export GNUPGHOME="$XDG_CONFIG_HOME/gnupg/"
  else
    echo "GNUPGHOME not found." >&2
  fi
fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
