#!/usr/bin/env bash
#

# PS2: Continuation prompt
# Default: '> '
export PS2="... "
# PS3: Option select prompt
# Default: '#?'
export PS3='#?'
# PS4: Script debug mode prefix
# Default: '+'
export PS4='+ ${FUNCNAME[0]:+${FUNCNAME[0]}():}line ${LINENO}: '

# EOF
