#!/usr/bin/env sh
#

if command -v pyenv >/dev/null 2>&1 ; then
  # (The below instructions are intended for common
  # shell setups. See the README for more guidance
  # if they don't apply and/or don't work for you.)

  # Add pyenv executable to PATH and
  # enable shims by adding the following
  # to ~/.profile:

  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"

  # If your ~/.profile sources ~/.bashrc,
  # the lines need to be inserted before the part
  # that does that. See the README for another option.

  # If you have ~/.bash_profile, make sure that it
  # also executes the above lines -- e.g. by
  # copying them there or by sourcing ~/.profile

  # Load pyenv into the shell by adding
  # the following to ~/.bashrc:

  eval "$(pyenv init -)"

  # Make sure to restart your entire logon session
  # for changes to profile files to take effect.

  # Use XDG spec for storing shims
  if [ "$(ostype)" != "macos" ]; then
    # This breaks on MacOS because stupid MacOS has whitespace in "Application Support"
    # as of this writing, stupid python can't build from paths with whitespace
    export PYENV_ROOT="${XDG_DATA_HOME:-${HOME}/.local/share}/pyenv"
  else
    export PYENV_ROOT="$HOME/.pyenv"
  fi
fi
