#!/usr/bin/env sh
#

if ! command -v adb >/dev/null 2>&1 ; then
    # Print debug information. A comma separated list of the following values 1 or
    # all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  export ADB_TRACE=""
    # The serial number to connect to. -s takes priority over this if given.
# export ANDROID_SERIAL=""
    # When used with the logcat option, only these debug tags are printed.
# export ANDROID_LOG_TAGS=
fi

# EOF
