#!/usr/bin/env sh
#

if command -v gpg >/dev/null 2>&1 ; then
    # Remember the current tty (so we don't bleed permissions?)
  GPG_TTY="$(tty)"
  export GPG_TTY
  if [ -d "$XDG_CONFIG_HOME/gnupg/" ] ; then
    export GNUPGHOME="$XDG_CONFIG_HOME/gnupg/"
  else
    echo "GNUPGHOME not found." >&2
  fi
fi

# EOF
