#!/usr/bin/env bash
#

bash_prompt="$HOME/.bash_prompt"

if [[ -f "$bash_prompt" ]]; then
  # shellcheck disable=SC1090
  source "$bash_prompt"
else
  echo "bash prompt not found: $bash_prompt" 1>&2
fi

# PS2: Continuation prompt
# Default: '> '
export PS2="... "
# PS3: Option select prompt
# Default: '#?'
export PS3='#?'
# PS4: Script debug mode prefix
# Default: '+'
export PS4='+ ${FUNCNAME[0]:+${FUNCNAME[0]}():}line ${LINENO}: '

# EOF
