#!/usr/bin/env sh

if [ -n "$(pacman -Q nvidia 2> /dev/null)" ]; then
  if [ -d "$XDG_CACHE_HOME/nvidia" ] ; then
    export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME/nvidia"
  else
    echo "__GL_SHADER_DISK_CACHE_PATH not found." >&2
  fi
  # Setting the environment variable __GL_SYNC_TO_VBLANK to a non-zero value
  # will force glXSwapBuffers to sync to your monitor's vertical refresh
  # (perform a swap only during the vertical blanking period).
  export __GL_SYNC_TO_VBLANK="0"
  # When using __GL_SYNC_TO_VBLANK with TwinView, OpenGL can only sync to one
  # of the display devices; this may cause tearing corruption on the display
  #  device to which OpenGL is not syncing. You can use the environment variable
  # __GL_SYNC_DISPLAY_DEVICE to specify to which display device OpenGL should
  # sync. You should set this environment variable to the name of a display
  # device; for example "CRT-1". Look for the line "Connected display
  # device(s):" in your X log file for a list of the display devices present
  # and their names. You may also find it useful to review Chapter 13,
  # Configuring TwinView "Configuring Twinview" and the section on Ensuring
  # Identical Mode Timings in Chapter 19, Programming Modes.
  # export __GL_SYNC_DISPLAY_DEVICE=""
fi

# EOF
