#!/usr/bin/env bash
#

lscolors_file="${XDG_DATA_HOME:-$HOME/.local/share}/lscolors.sh"

if [[ -s "$lscolors_file" ]] ; then
  # shellcheck disable=SC1090
  source "$lscolors_file"
else
  echo "LS_COLORS file not found: $lscolors_file" 1>&2
fi

# EOF
