#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  git config --global user.name "Ryan Delaney" || return 1
  if [ -r "$HOME"/.emailaddress ] ; then
    email_address="$(cat "$HOME"/.emailaddress)"
  else
    email_address="ryan.delaney@gmail.com"
  fi
  git config --global user.email "$email_address" || return 1
  git config --global core.excludesfile "/home/ryan/.config/git/ignore" || return 1
  git config --global core.whitespace "trailing-space,space-before-tab" || return 1
  git config --global core.filemode "true" || return 1
  git config --global core.symlinks "true" || return 1
  git config --global push.default "tracking" || return 1
  git config --global branch.autosetuprebase "never" || return 1
  # diff {{{1
  git config --global diff.tool "vimdiff" || return 1
  git config --global diff.renames "copies" || return 1
  git config --global diff.mnemonicprefix "true" || return 1
  git config --global difftool.prompt "true" || return 1
  # 1}}} diff
  # Merge {{{1
  git config --global merge.tool "vimdiff" || return 1
  git config --global merge.conflictstyle "diff3" || return 1
  git config --global mergetool.prompt "true" || return 1
  # 1}}} Merge
  git config --global pager.diff "less" || return 1
  # Alias {{{1
  git config --global alias.ls 'log --pretty=format:%C(yellow)%h%Cred%d\ %Creset%s%Cblue\ [%cn] --decorate --no-merges' || return 1
  git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset' --abbrev-commit" || return 1
  git config --global alias.lgd 'log --pretty=format:%C(yellow)%h\ %ad%Cred%d\ %Creset%s%Cblue\ [%cn] --decorate --date=short' || return 1
  git config --global alias.d "difftool -t vimdiff" || return 1
  git config --global alias.f "fetch" || return 1
  git config --global alias.fa "fetch --all --recurse-submodules=on-demand" || return 1
  git config --global alias.fd "fetch --dry-run" || return 1
  git config --global alias.fp "fetch --prune" || return 1
  git config --global alias.fap "fetch --all --prune --recurse-submodules=on-demand" || return 1
  git config --global alias.m "merge" || return 1
  git config --global alias.mt "mergetool -t vimdiff" || return 1
  git config --global alias.cp "cherry-pick" || return 1
  git config --global alias.dc "difftool -t vimdiff --cached" || return 1
  git config --global alias.ours 'f() { git checkout --ours $@ && git add $@; }; f' || return 1
  git config --global alias.theirs 'f() { git checkout --theirs $@ && git add $@; }; f' || return 1
  git config --global alias.cl "clone" || return 1
  git config --global alias.remotes "remote -v" || return 1
  git config --global alias.s "status -s" || return 1
  git config --global alias.st "status" || return 1
  git config --global alias.sp "status --porcelain" || return 1
  git config --global alias.c "commit" || return 1
  git config --global alias.cs "commit -S" || return 1
  git config --global alias.tags "tag --list -n3" || return 1
  git config --global alias.co "checkout" || return 1
  git config --global alias.br "branch -v" || return 1
  git config --global alias.bra "branch -va" || return 1
  git config --global alias.r "reset" || return 1
  git config --global alias.find "git ls-files | grep -i" || return 1
  git config --global alias.g "grep --color=auto --perl-regexp --full-name --heading --break --line-number -I" || return 1
  git config --global alias.leaders "shortlog -sn --all --no-merges" || return 1
  # 1}}} Alias
  # Color {{{1
  git config --global color.diff "auto" || return 1
  git config --global color.status "auto" || return 1
  git config --global color.branch "auto" || return 1
  git config --global color.interactive "auto" || return 1
  git config --global color.ui "auto" || return 1
  git config --global color.branch.current "green bold" || return 1
  git config --global color.branch.local "green" || return 1
  git config --global color.branch.remote "red bold" || return 1
  git config --global color.diff.meta "yellow bold" || return 1
  git config --global color.diff.frag "magenta bold" || return 1
  git config --global color.diff.old "red bold" || return 1
  git config --global color.diff.new "green bold" || return 1
  git config --global color.status.added "green bold" || return 1
  git config --global color.status.changed "yellow bold" || return 1
  git config --global color.status.untracked "red bold" || return 1
  git config --global color.sh.branch "yellow" || return 1
  # 1}}} Color
  # Advice {{{1
  git config --global advice.pushnonffcurrent "true" || return 1
  git config --global advice.pushnonffdefault "true" || return 1
  git config --global advice.pushnonffmatching "true" || return 1
  git config --global advice.pushalreadyexists "true" || return 1
  git config --global advice.pushfetchfirst "true" || return 1
  git config --global advice.pushneedsforce "true" || return 1
  git config --global advice.statushints "false" || return 1
  git config --global advice.statusuoption "true" || return 1
  git config --global advice.commitbeforemerge "false" || return 1
  git config --global advice.resolveconflict "true" || return 1
  git config --global advice.implicitidentity "true" || return 1
  git config --global advice.detachedhead "false" || return 1
  git config --global advice.amworkdir "true" || return 1
  git config --global advice.rmhints "true" || return 1
  # 1}}} Advice
  # GUI {{{1
  git config --global gui.wmstate "normal" || return 1
  git config --global gui.geometry "1920x1014+1680+18 192 177" || return 1
  # 1}}} GUI
  # URL replacements {{{1
  git config --global --replace-all url."git@github.com:".insteadof "github:" || return 1
  git config --global --replace-all url."https://github.com:".insteadof "http://github.com/" || return 1
  git config --global --replace-all url."https://gitlab.com:".insteadof "http://gitlab.com/" || return 1
  git config --global --replace-all url."https://notabug.org:".insteadof "http://notabug.org/" || return 1
  git config --global --replace-all diff.gpg.textconv "gpg --no-tty --decrypt" || return 1
  # 1}}} URL replacements
}

main "$@"
return "$?"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
