#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if command -v pager >/dev/null 2>&1 ; then
  export PAGER="pager"
elif command -v most >/dev/null 2>&1 ; then
  export PAGER="most"
  export MOST_EDITOR="vim"
  if [ -f "$XDG_CONFIG_HOME/most/mostrc" ] ; then
    export MOST_INITFILE="$XDG_CONFIG_HOME/most/mostrc"
  else
    echo "MOST_INITFILE not found." >&2
  fi
elif command -v less >/dev/null 2>&1 ; then
  export PAGER="less"
  export LESSHISTSIZE="0"
  export LESSEDIT="vim"
fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
