#!/usr/bin/env sh
#

  # If this parameter is set to a filename or directory name and the MAILPATH
  # variable is not set, Bash informs the user of the arrival of mail in the
  # specified file or Maildir-format directory.
if [ -n "$USER" ] && [ -e "/var/mail/$USER" ] ; then
  export MAIL="/var/mail/$USER"
else
  echo "MAIL not found." >&2
fi

  # How often (in seconds) that the shell should check for mail in the files
  # specified in the MAILPATH or MAIL variables. The default is 60 seconds. When
  # it is time to check for mail, the shell does so before displaying the primary
  # prompt. If this variable is unset, or set to a value that is not a number
  # greater than or equal to zero, the shell disables mail checking.
export MAILCHECK=60

if command -v mutt >/dev/null 2>&1 ; then
  if [ -d "$GNUPGHOME" ] && [ -x "$GNUPGHOME" ] ; then
    export PGPPATH="$GNUPGHOME"
  else
    echo "PGPPATH not found." >&2
  fi
  if [ ! -d "$TMPDIR" ] && [ -d "/tmp/" ] && [ -x "/tmp/" ] ; then
    export TMPDIR="/tmp/"
  else
    echo "TMPDIR not found." >&2
  fi
  # Full  path  of  the  user's  spool mailbox if MAIL is unset.  Commonly used
  # when the spool mailbox is a maildir (5) folder.
  if [ -d "/var/mail/ " ] && [ -x "/var/mail/" ] ; then
    export MAILDIR="/var/mail/"
  else
    echo "MAILDIR not found." >&2
  fi
fi

# EOF
