#!/usr/bin/env sh
#

if command -v pager >/dev/null 2>&1 ; then
  export PAGER="pager"
elif command -v most >/dev/null 2>&1 ; then
  export PAGER="most"
  export MOST_EDITOR="vim"
  if [ -f "$XDG_CONFIG_HOME/most/mostrc" ] ; then
    export MOST_INITFILE="$XDG_CONFIG_HOME/most/mostrc"
  else
    echo "MOST_INITFILE not found." >&2
  fi
elif command -v less >/dev/null 2>&1 ; then
  export PAGER="less"
  export LESSHISTSIZE="0"
  export LESSEDIT="vim"
fi

# EOF
