#!/usr/bin/env sh
#

main() {
  # shellcheck disable=SC1090
  if [ -s "$HOME/.rvm/scripts/rvm" ] ; then
    # shellcheck disable=SC1091
    . "$HOME/.rvm/scripts/rvm" || return
  fi
}

main "$@"

# EOF
