#!/usr/bin/env sh
# GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

# silence warnings about SC1090:
# shellcheck source=/dev/null

if ! command -v hostname >/dev/null 2>&1 ; then echo "Missing dependency: hostname" 1>&2 ; exit 1 ; fi
_hostname="$(hostname)"

  # determine if we want to run a new ssh-agent for this session
if command -v keychain >/dev/null 2>&1 ; then
  keychain --noask --nogui --quick
  [ -f "$HOME/.keychain/$_hostname"-sh ]      && . "$HOME/.keychain/$_hostname"-sh
  [ -f "$HOME/.keychain/$_hostname"-sh-gpg ]  && . "$HOME/.keychain/$_hostname"-sh-gpg
  keychain -l | column -t
else
  echo "keychain(1) not found."
fi

# EOF
