#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

install_dir="$HOME/.dotfiles/install.d"
install_files="$install_dir/*"

if [[ -z $dotfiles_dest ]]; then
  export dotfiles_dest="$HOME/.dotfiles"
fi

if [[ ! -x "$install_dir" ]]; then echo "Install scripts directory not found: $install_dir" 1>&2; exit 1; fi

# Get the ostype and distro if applicable
ostype="$(ostype)"
[[ "$ostype" == "linux" ]] && distro="$(distro)"

installd_exec() {
  local script
  script="$1"

  # shellcheck disable=SC1090
  if ! source "$script" ; then
    echo "Installation error with $script" 1>&2
    echo "Aborting." 1>&2
    exit 1
  fi
}

main() {
  for script in $install_files ; do
    local platform
    platform=$(basename "$script" | cut -f 2 -d'-')

    case "$platform" in
      "all")
        installd_exec "$script"
        ;;
      "$ostype")
        installd_exec "$script"
        ;;
      "$distro")
        installd_exec "$script"
        ;;
      * )
        : ;;
    esac
  done
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
