#!/usr/bin/env bash
#

install_dir="$HOME/.dotfiles/install.d"

if [[ -z $dotfiles_dest ]]; then
  export dotfiles_dest="$HOME/.dotfiles"
fi

if [[ ! -x "$install_dir" ]]; then echo "Install scripts directory not found: $install_dir" 1>&2; exit 1; fi

# Get the ostype and distro if applicable
ostype="$(ostype)"
[[ "$ostype" == "linux" ]] && distro="$(distro)"

installd_exec() {
  local script
  script="$1"

  # shellcheck disable=SC1090
  if ! source "$script" ; then
    echo "Installation error with $script" 1>&2
    echo "Aborting." 1>&2
    exit 1
  fi
}

main() {
  for script in "$install_dir"/* ; do
    local platform
    platform=$(basename "$script" | cut -f 2 -d'-')

    case "$platform" in
      "all")
        installd_exec "$script"
        ;;
      "$ostype")
        installd_exec "$script"
        ;;
      "$distro")
        installd_exec "$script"
        ;;
      * )
        : ;;
    esac
  done
}

main "$@"

# EOF
