#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

dotfiles_dest="$HOME/.dotfiles"
dotfiles_repo='git://github.com/rpdelaney/dotfiles'

if [[ ! -r install ]]; then echo "Missing dependency: install" 1>&2; exit 1; fi

if ! command -v git &> /dev/null; then
  echo "Missing dependency: git" 1>&2
  if [[ "$OSTYPE" =~ ^darwin ]]; then
    # shellcheck disable=SC2016
    echo 'Consider `xcode-select --install` to get a barebones git.' 1>&2
  fi
  exit 1
fi

main() {
  if [[ ! -d "$dotfiles_dest" ]]; then
    git clone "$dotfiles_repo" "$dotfiles_dest" || exit 1
    cd "$dotfiles_dest" || exit 1
  fi

  git pull origin master
  bash install
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
