#!/usr/bin/env bash
#

dotfiles_repo='git://github.com/rpdelaney/dotfiles'

if [[ ! -s install ]]; then echo "Missing dependency: install" 1>&2; exit 1; fi

if ! command -v git &> /dev/null; then
  echo "Missing dependency: git" 1>&2
  if [[ "$OSTYPE" =~ ^darwin ]]; then
    # shellcheck disable=SC2016
    echo 'Consider `xcode-select --install` to get a barebones git.' 1>&2
  fi
  exit 1
fi

main() {
  if [[ ! -d "$HOME/.dotfiles" ]]; then
    git clone --recurse-submodules --jobs 8 "$dotfiles_repo" "$HOME/.dotfiles" || exit
  fi

  if cd "$HOME/.dotfiles" ; then
    git pull origin master || return
    ./scripts/setup_hooks || return
    git config --local user.name 'Ryan Delaney'
    git config --local user.email 'ryan.patrick.delaney@protonmail.com'
    bash install
  fi
}

main "$@"
