#!/usr/bin/env bash
# GNU bash, version 4.2.45(2)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014-02-12 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# don't type passwords a bunch of times when using git as a glorified backup tool.
# we are lazy.
#

message="$(curl -s http://whatthecommit.com/index.txt)"
if [[ "$message" == "" ]]; then message="this update is unusually unfunny"; fi

    # if there's a keychain, then double-check that it has been run on the current env
[[ $(type keychain 2> /dev/null) ]] && keychain -q

    # if there's still no identity in ssh-agent, add it
if [[ $(ssh-add -L) == "The agent has no identities." ]]; then
    if type -p cowsay; then
        cowsay "Identify yourself."
    else
        echo "Identify yourself."
    fi
    ssh-add -t 12h "$HOME/.ssh/id_rsa"
fi

    # now that we have ssh kanged up, upload our crap
if ! git add . -A; then echo 'FATAL: Git add failed. WTF have you done?'; exit 1; fi
git status
confirm || exit 1
git commit -m "$message" && git pull && git push
