#!/usr/bin/env bash
#
# don't type passwords a bunch of times. we are lazy.
#

message="$(curl -s http://whatthecommit.com/index.txt)"
if [[ "$message" == "" ]]; then message="this update is unusually unfunny"; fi

    # if there's a keychain, then double-check that it has been run on the current env
[[ $(type keychain 2> /dev/null) ]] && keychain -q

    # if there's still no identity in ssh-agent, add it
if [[ $(ssh-add -L) == "The agent has no identities." ]]; then
    if type -p cowsay; then
        cowsay "Identify yourself."
    else
        echo "Identify yourself."
    fi
    ssh-add -t 12h ${HOME}/.ssh/id_rsa
fi

    # now that we have ssh kanged up, upload our crap
git add . -A
git status
confirm || exit 1
git commit -m "$message"
git pull
git push
