[tool.ruff]
target-version = "py312"

line-length = 79


exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint]
select = [ "ALL" ]
ignore = [
    "ANN101",
    "D203",   # prefer D211 `no-blank-line-before-class`
    "D213",   # prefer D212 `multi-line-summary-first-line`
]
fixable = [ "ALL" ]
unfixable = [
    "F401",
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules {{{1
    "COM812",
    "COM819",
    "D206",
    "D300",
    "E111",
    "E114",
    "E117",
    "ISC001",
    "ISC002",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "W191",
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules 1}}}
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs}/*" = [
    "ARG",
    "ANN",
    "D",
    "S",
]

[tool.ruff.lint.isort]
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
force-single-line = false
force-wrap-aliases = false
lines-after-imports = false
lines-between-types = false
split-on-trailing-comma = false

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
exclude = [
    "*.pyi",
]
