[tool.ruff]
target-version = "py312"

line-length = 79

[tool.ruff.lint]
select = [
    "ALL"
]
ignore = [
    "D203",  # prefer D211 `no-blank-line-before-class`
    "D213",  # prefer D212 `multi-line-summary-first-line`
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "ALL"
]
unfixable = [
    "F401"
]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
exclude = ["*.pyi"]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
