globinclude conf.d/**/*.conf


# BEGIN_KITTY_FONTS
font_family      family="Iosevka Custom 15"
bold_font        family='Iosevka Custom 15' postscript_name=Iosevka-Custom-15-Bold
italic_font      family='Iosevka Custom 15' postscript_name=Iosevka-Custom-15-Oblique
bold_italic_font family='Iosevka Custom 15' postscript_name=Iosevka-Custom-15-Bold-Oblique
# END_KITTY_FONTS