#!/usr/bin/env sh
#

bin_dest="$HOME"/bin
bin_repo='git://github.com/rpdelaney/dotfiles'

if [ -d "$bin_dest" ]; then
  echo "bin destination dir already exists: $bin_dest" 1>&2
  return 1
fi

main() {
    git clone --recurse-submodules --jobs 8 "$bin_repo" "$bin_dest" || return $?
    ( cd "$bin_dest" && { git config --local user.email 'ryan.patrick.delaney@protonmail.com' ; git config --local user.name 'Ryan Delaney' ; } )
}

main "$@"

# EOF
