#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
bin_dest="$HOME"/bin
bin_repo='git://github.com/rpdelaney/dotfiles'

if [ -d "$bin_dest" ]; then
  echo "bin destination dir already exists: $bin_dest" 1>&2
  return 1
fi

main() {
    git clone --recurse-submodules --jobs 8 "$bin_repo" "$bin_dest" || return $?
    ( cd "$bin_dest" && { git config --local user.email 'ryan.delaney@gmail.com' ; git config --local user.name 'Ryan Delaney' ; } )
}

main "$@"

# EOF
