#!/usr/bin/env bash
# software.
#

main() {
  # Power Settings for all Users (Display Sleep, Workstation Sleep, Wake for
  # network access)
  #     Pmset -a = All Power modes
  #     Pmset -c = A/C Power
  #     Pmset -b = Battery Power
  # to copy preferences in a less painful manner:
  #     "pmset -g" awk 1 ORS='' | tr -s ' ' > ~/FileToEdit
  # note: you will need to prune some of the output

  # this will set up the battery settings
  sudo pmset -b \
    autopoweroff 1 \
    autopoweroffdelay 14400 \
    darkwakes 0 \
    disksleep 0 \
    displaysleep 0 \
    halfdim 1 \
    hibernatefile /var/vm/sleepimage \
    hibernatemode 25 \
    sleep 0 \
    standby 1 \
    standbydelay 10800 \
    ttyskeepawake 1

  # This will set up the ac power settings
  sudo pmset -a \
    acwake 0 \
    autopoweroff 1 \
    autopoweroffdelay 14400 \
    darkwakes 0 \
    disksleep 0 \
    displaysleep 0 \
    halfdim 1 \
    hibernatemode 3 \
    lidwake 1
    sleep 0 \
    standby 1 \
    standbydelay 10800 \
    ttyskeepawake
}

main "$@"

# EOF
