#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  # Power Settings for all Users (Display Sleep, Workstation Sleep, Wake for
  # network access)
  #     Pmset -a = All Power modes
  #     Pmset -c = A/C Power
  #     Pmset -b = Battery Power
  # to copy preferences in a less painful manner:
  #     "pmset -g" awk 1 ORS='' | tr -s ' ' > ~/FileToEdit
  # note: you will need to prune some of the output

  # this will set up the battery settings
  sudo pmset -b \
    standbydelay 10800 \
    standby 1 \
    halfdim 1 \
    hibernatefile /var/vm/sleepimage \
    darkwakes 0 \
    disksleep 0 \
    sleep 0 \
    autopoweroffdelay 14400 \
    hibernatemode 3 \
    autopoweroff 1 \
    ttyskeepawake 1 \
    displaysleep 0

  # This will set up the ac power settings
  sudo pmset -a \
    standbydelay 10800 \
    standby 1 \
    halfdim 1 \
    darkwakes 0 \
    disksleep 0 \
    sleep 0 \
    autopoweroffdelay 14400 \
    hibernatemode 3 \
    autopoweroff 1 \
    ttyskeepawake 1 \
    displaysleep 0 \
    acwake 0 \
    lidwake 1
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
