#!/usr/bin/env bash
# shellcheck disable=SC2174
#

mkdir --parents --mode=0700 "$HOME/.cache/" && export XDG_CACHE_HOME="$HOME/.cache/"
mkdir --parents --mode=0700 "$HOME/.config/" && export XDG_CONFIG_HOME="$HOME/.config/"
mkdir --parents --mode=0700 "$HOME/.local/share" && export XDG_DATA_HOME="$HOME/.local/share"
