#!/usr/bin/env bash
# shellcheck disable=SC2174
#

main() {
  mkdir -p -m 0700 "$HOME/Caches/" || return $?
  export XDG_CACHE_HOME="$HOME/Caches/"
  mkdir -p -m 0700 "$HOME/Preferences/" || return $?
  export XDG_CONFIG_HOME="$HOME/Preferences/"
  mkdir -p -m 0700 "$HOME/Library/Application Support/" || return $?
  export XDG_DATA_HOME="$HOME/Library/Application Support/"
}

main "$@"

# EOF
