#!/usr/bin/env bash
#

if ! command -v find &> /dev/null; then echo "Missing dependency: find" 1>&2; return 1; fi

main() {
  (
    if cd "$HOME" ; then
      find ".dotfiles/home/" -maxdepth 1 -mindepth 1 -exec ln -s {} \;
    fi
  )
}

main "$@"

# EOF
