#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  ###############################################################################
  # Mice, keyboard, etc                                                         #
  ###############################################################################
  # Set a blazingly fast keyboard repeat rate (default 300)
# defaults write NSGlobalDomain KeyRepeat -int 50

  # disable Natural scrolling
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

  # stop Photos from opening automatically
  defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
}

main "$@" || return $?
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
