#!/usr/bin/env bash
#

main() {
  ###############################################################################
  # Mice, keyboard, etc                                                         #
  ###############################################################################
  # Set a blazingly fast keyboard repeat rate (default 300)
  defaults write -g InitialKeyRepeat -int 25 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

  # disable Natural scrolling
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

  # stop Photos from opening automatically
  defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
}

main "$@"

# EOF
