#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2019 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  # Faster Dock
  defaults write com.apple.Dock autohide-delay -float 0.1
  defaults write com.apple.dock autohide-time-modifier -float 0.5

  #
  defaults write com.apple.dock largesize -float 150.000000

  #
  defaults write com.apple.dock static-only -bool TRUE;

  # Automatically hide and show the Dock
  defaults write com.apple.dock autohide -bool true

  # Enable gestures
  defaults write com.apple.dock scroll-to-open -bool TRUE; killall Dock

  # Make Dock icons of hidden applications translucent
  defaults write com.apple.dock showhidden -bool true

  # Dim hidden apps
  defaults write com.apple.dock showhidden -bool TRUE; killall Dock

  # Don't rearrange Spaces based on most recent use
  defaults write com.apple.dock mru-spaces -boolean NO

  # Kill the dock, so that it will restart and all changes should be observed
  killall Dock
}

main "$@"

# EOF
