#!/usr/bin/env bash
#

if ! command -v brew &> /dev/null; then echo "Missing dependency: brew" 1>&2; return 1; fi

cask_install() {
  local app
  app="$1"

  brew cask install "$app"
}

main() {
  for cask in "${casks[@]}"; do
    cask_install "$cask"
  done

  brew cleanup
}

casks=(
  1password
  1password-cli
  electric-sheep
  firefox
  font-consolas-for-powerline
  font-inconsolata-g-for-powerline
  kitty
  marmaduke-chromium-ungoogled
  muzzle
  osxfuse
  scroll-reverser
  signal
  visual-studio-code
  xquartz
)

main "$@"

# EOF
