#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if ! command -v brew &> /dev/null; then echo "Missing dependency: brew" 1>&2; return 1; fi

cask_install() {
  local app
  app="$1"

  brew cask install "$app" || return $?
}

main() {
  for cask in "${casks[@]}"; do
    cask_install "$cask"
  done

  brew cleanup
}

casks=(
  1password
  1password-cli
  electric-sheep
  firefox
  font-consolas-for-powerline
  font-inconsolata-g-for-powerline
  kitty
  muzzle
  osxfuse
  scroll-reverser
  signal
  visual-studio-code
  xquartz
)

main "$@" || return $?
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
