#!/usr/bin/env bash
#

if ! command -v brew &> /dev/null; then echo "Missing dependency: brew" 1>&2; return 1; fi

cask_install() {
  local app
  app="$1"

  brew install "$app"
}

main() {
  for cask in "${casks[@]}"; do
    cask_install "$cask" || break
  done

  brew cleanup
}

casks=(
  font-consolas-for-powerline
  font-inconsolata-g-for-powerline
  kitty
  muzzle
  scroll-reverser
)

main "$@"

# EOF
