#!/usr/bin/env dash
#

if ! command -v mktemp 1> /dev/null 2>&1 ; then echo "Missing dependency: mktemp" 1>&2; return 1; fi
tmpdir=$(dirname "$(mktemp -u || return 1)")

main() {
  # install 'yay'
  # https://github.com/Jguer/yay
  if cd "$tmpdir" ; then
    if git clone https://aur.archlinux.org/yay.git ; then
      cd yay && makepkg --install --needed --syncdeps --noconfirm
    fi
  fi
}

main "$@"

# EOF
