#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  # Ignore if we're not on OSX
  [[ "$OSTYPE" =~ ^darwin ]] || return 0

  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || return $?

  brew analytics off || return $?

  brew tap homebrew/cask-fonts || return $?
  brew tap homebrew/command-not-found || return $?
}

main "$@" || return $?
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
