#!/usr/bin/env bash
#

if ! command -v pip2 &> /dev/null; then echo "Missing dependency: pip2" 1>&2; return 1; fi
if ! command -v pip3 &> /dev/null; then echo "Missing dependency: pip3" 1>&3; return 1; fi

python3apps=(
  black
  ptpython
  daff
  flake8
  pudb
  pwstore
  twine
  mypy
  yamllint
)

flake8_injects=(
  flake8-bandit
  flake8-bugbear
  flake8-simplify
)

main() {
  for targetapp in "${python3apps[@]}"; do
    pipx install "$targetapp" || return
  done

  for inject in "${flake8_injects[@]}"; do
    pipx inject flake8 "$inject" || return
  done
}

main "$@"

# EOF
