#!/usr/bin/env bash
#

if ! command -v pip2 &> /dev/null; then echo "Missing dependency: pip2" 1>&2; return 1; fi
if ! command -v pip3 &> /dev/null; then echo "Missing dependency: pip3" 1>&3; return 1; fi

python2apps=(
  daff
  pudb
)

python3apps=(
  bpython
  flake8
  flake8-bandit
  flake8-bugbear
  flake8-confusables
  flake8-pytest
  flake8-mutable
  flake8-return
  pwstore
  setuptools
  twine
  wheel
)

p2install() {
  local targetapp
  targetapp="$1"

  pip2 install --user "$targetapp"
}

p3install() {
  local targetapp
  targetapp="$1"

  pip3 install --user "$targetapp"
}

main() {
  for p2app in "${python2apps[@]}"; do
    p2install "$p2app" || return $?
  done

  for p3app in "${python3apps[@]}"; do
    p3install "$p3app" || return $?
  done
}

main "$@"

# EOF
