#!/usr/bin/env bash
#

if ! command -v brew &> /dev/null; then echo "Missing dependency: brew" 1>&2; return 1; fi

brew_install() {
  local app
  app="$1"

  # shellcheck disable=SC2086
  brew install --display-times $app
}

main() {
  for app in "${homebrew_apps[@]}"; do
    if ! brew_install "$app" ; then
      echo "ERROR: (exit code $?) Failed to install $app" 1>&2
    fi
  done

  brew cleanup
}

homebrew_apps=(
  'aspell --with-all-langs'
  'base64'
  'bash'
  'bash-completion'
  'binutils'
  'brew-cask-completion'
  'checkbashisms'
  'cmake'
  'colordiff'
  'coreutils'
  'curl --with-libssh2 --with-gssapi --with-rtmpdump'
  'dateutils'
  'dialog'
  'diffutils'
  'direnv'
  'docx2txt'
  'dos2unix'
  'enca'
  'espeak'
  'exa'
  'exiftool'
  'file-formula'
  'findutils --with-default-names'
  'flake8'
  'gcc'
  'gem-completion'
  'ghostscript'
  'git --with-curl --with-openssl'
  'glances'
  'gnu-indent --with-default-names'
  'gnu-sed --with-default-names'
  'gnu-tar --with-default-names'
  'gnu-which --with-default-names'
  'gnupg'
  'golang'
  'grc'
  'grep --with-default-names'
  'gzip'
  'hashdeep'
  'htop --with-ncurses'
  'hub'
  'imagemagick'
  'inetutils --with-default-names'
  'jq'
  'keychain'
  'less --with-pcre'
  'lesspipe'
  'libqalculate'
  'mailutils'
  'make --with-default-names'
  'mas'
  'media-info'
  'moreutils'
  'ncdu'
  'ncurses'
  'nmap'
  'open-completion'
  'openssh'
  'openvpn'
  'pandoc'
  'pip-completion'
  'pipenv'
  'proctools'
  'psgrep'
  'pv'
  'pwgen'
  'pyenv'
  'ranger'
  'rst-lint'
  'rsync'
  'ruby'
  'ruby-completion'
  'shellcheck'
  'sox --with-libao --with-libsndfile --with-opencore-amr --with-opusfile'
  'sshfs'
  'sxiv'
  'terminal-notifier'
  'tig'
  'tmux'
  'tree'
  'unar'
  'util-linux'
  'vim --with-client-server --with-gettext --with-luajit --with-override-system-vi --with-tcl'
  'vimpager --with-pandoc'
  'w3m'
  'watch'
  'weechat --with-aspell --with-curl --with-lua --with-perl --with-python@2 --with-ruby'
  'wget --with-gpgme --with-libmetalink --with-pcre'
)


main "$@"

# EOF
