#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if ! command -v brew &> /dev/null; then echo "Missing dependency: brew" 1>&2; return 1; fi

brew_install() {
  local app
  app="$1"

  brew install "$app" || return $?
}

main() {
  for app in "${homebrew_apps[@]}"; do
    brew_install "$app"
  done

  brew cleanup
}

homebrew_apps=(
  aspell --with-all-langs
  atool
  awscli
  baobab
  base64
  bash
  bash-completion
  binutils
  brew-cask-completion
  checkbashisms
  cmake
  colordiff
  coreutils
  csvkit
  curl --with-libssh2 --with-gssapi --with-rtmpdump
  dateutils
  dialog
  diffutils
  direnv
  docx2txt
  dos2unix
  enca
  encfs
  espeak
  exa
  exiftool
  file-formula
  findutils --with-default-names
  flake8
  gcc
  gem-completion
  git --with-curl --with-openssl
  glances
  gnu-indent --with-default-names
  gnu-sed --with-default-names
  gnu-tar --with-default-names
  gnu-which --with-default-names
  gnupg
  golang
  grc
  grep --with-default-names
  gzip
  hashdeep
  htop --with-ncurses
  hub
  imagemagick
  inetutils --with-default-names
  jq
  keychain
  ksh
  less --with-pcre
  lesspipe --with-syntax-highlighting
  libnotify
  libqalculate
  lynx
  mailutils
  make --with-default-names
  media-info
  moreutils
  mosh
  mps-youtube
  ncdu
  ncurses
  nmap
  open-completion
  openssh
  openvpn
  pandoc
  pip-completion
  pipenv
  proctools
  psgrep
  pv
  pwgen
  pyenv
  qrencode
  ranger
  rsync
  ruby
  ruby-completion
  sendemail
  shellcheck
  sox --with-libao --with-libsndfile --with-opencore-amr --with-opusfile
  sshfs
  sxiv
  terminal-notifier
  terraform
  terraform-docs
  terraform_landscape
  tig
  tmux
  tor --with-libscrypt
  torsocks
  tree
  unar
  util-linux
  vim --with-client-server --with-gettext --with-luajit --with-override-system-vi --with-tcl
  vimpager --with-pandoc
  w3m
  watch
  weechat --with-aspell --with-curl --with-lua --with-perl --with-python@2 --with-ruby
  wget --with-gpgme --with-libmetalink --with-pcre
  wine
  zsh --with-gdbm --with-pcre
  zsh-autosuggestions
  zsh-completions
  zshdb
)


main "$@" || return $?
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
