#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

# shellcheck disable=SC2154
if [[ ! -d "$dotfiles_dest" ]] ; then
  echo "FATAL: dotfiles_dest is not found. I don't know what to do." 1>&2
  return 1
fi

main() {
  pip3 install pre-commit || return $?

  cd "$dotfiles_dest" || return $?
  pre-commit install || return $?
}

main "$@" || return "$?"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
