#!/usr/bin/env bash
#

inconsolata_url='https://github.com/powerline/fonts/blob/master/Inconsolata-g/Inconsolata-g%20for%20Powerline.otf?raw=true'
inconsolata_file='Inconsolata-g_for_powerline.otf'
system_fonts_dir='/Library/Fonts/'

main() {
  cd "$TMP" || return $?
  curl -L -s "$inconsolata_url" > "$inconsolata_file" || return $?
  cp "$inconsolata_file" "$system_fonts_dir"
}

main "$@"

# EOF
