#!/usr/bin/env sh
#

authorized_users_dir="$HOME/.ssh/"
authorized_users_file="$authorized_users_dir"/authorized_users
authorized_users_url='https://gist.githubusercontent.com/rpdelaney/c747e45ed2326f43331fb1650bbc7d92/raw/d824431abe8e820a680e848927d35421a3aed9ec/authorized_users'

main() {
  if [ -d "$authorized_users_dir" ] && [ -x "$authorized_users_dir" ] ; then
    curl -s "$authorized_users_url" >> "$authorized_users_file" || return $?
    vim "$authorized_users_file" -c 'sort u' -c 'wq!'
  else
    echo "WARNING: ssh directory not found: $authorized_users_dir" 1>&2
  fi
}

main "$@"

# EOF
