#!/usr/bin/env bash
#

if ! command -v vim &> /dev/null; then echo "Missing dependency: vim" 1>&2; return 1; fi

if ! [[ -d "$HOME/.vim/" ]] ; then
  echo "Directory not found: $HOME/.vim/" 1>&2
  return 1
fi

if ! [[ -r "$HOME/.vim/autoload/plug.vim" ]] ; then
  echo "File not found: $HOME/.vim/autoload/plug.vim" 1>&2
  return 1
fi

main() {
  # Upgrade & update vim-plug
  vim -c "PlugUpgrade" -c "PlugUpdate"
}

main "$@"

# EOF
