#!/usr/bin/env bash
#

if ! command -v nvim &> /dev/null; then echo "Missing dependency: nvim" 1>&2; return 1; fi

pynvim_env="$HOME/.local/share/nvim/venv"

main() {
  if [[ -d "$pynvim_env" ]]; then
    # assume it's already set up
    return 0
  fi

  mkdir -p "$pynvim_env" || return

  # Create a new virtual environment for Neovim
  python3 -m venv "$pynvim_env" || return

  # Activate it and install neovim package
  # shellcheck disable=1090
  source ~/.local/share/nvim/venv/bin/activate && python3 -m pip install pynvim
}

main "$@"

# EOF
