#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

# shellcheck disable=SC2154
if [[ -z $dotfiles_dest ]]; then echo "XDG env var is unset: dotfiles_dest" 1>&2; exit 1; fi

main() {
  cd "$HOME" || exit 1
  if ! command -v find &> /dev/null; then echo "Missing dependency: find" 1>&2; exit 1; fi
  find "$dotfiles_dest/$HOME" -maxdepth 1 -mindepth 1 -exec ln -s {} \;
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
