#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if [[ -z "$HOME" ]] || [[ ! -x "$HOME" ]]; then
  # shellcheck disable=SC2016
  echo '$HOME is unset or unreadable: '"$HOME"
fi

main() {
  if [[ "$OSTYPE" =~ ^darwin ]]; then
    # we are on macos
    export XDG_CACHE_HOME="$HOME/Caches/"
    export XDG_CONFIG_HOME="$HOME/Preferences/"
    export XDG_DATA_HOME="$HOME/Application Support/"
  else
    # we're probably on linux
    export XDG_CACHE_HOME="$HOME/.cache/"
    export XDG_CONFIG_HOME="$HOME/.config/"
    export XDG_DATA_HOME="$HOME/.local/share"
  fi
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
