#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if ! crontab -l > /dev/null ; then
  crontaburl="https://gist.githubusercontent.com/rpdelaney/2ec7b518390f87090f3f5f356c258942/raw/77fbc079b1212bd0dc4e47406363f64aedd27183/crontab.header"
  echo "Installing crontab header..."
  crontab < <(curl -s "$crontaburl" || return $?)
fi

# EOF
