#!/usr/bin/env bash
#

default_shell="/opt/homebrew/bin/bash"

if [[ ! -x "$default_shell" ]] ; then
  echo "FATAL: Default shell not found: $default_shell" 1>&2
  return 1
fi

main() {
  echo "Installing $default_shell as the default shell for $USER"
  echo "$default_shell" | sudo tee -a /etc/shells || return $?
  sudo chsh -s "$default_shell"
}

main "$@"

# EOF
