#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

# imports tmux-256color terminfo

x_txt="${dotfiles_dest:-$HOME/.dotfiles/}"/data/x.txt

main() {
  if [[ -s "$x_txt" ]] ; then
    tic -x "$x_txt"
  else
    echo "WARNING: tmux-256color terminfo not found: $x_txt"
  fi
}

main "$@"

# EOF
