#!/usr/bin/env bash
#

# imports tmux-256color terminfo

x_txt="${dotfiles_dest:-$HOME/.dotfiles/}"/data/x.txt

main() {
  if [[ -s "$x_txt" ]] ; then
    tic -x "$x_txt"
  else
    echo "WARNING: tmux-256color terminfo not found: $x_txt"
  fi
}

main "$@"

# EOF
