#!/usr/bin/env bash
#

# imports tmux-256color terminfo

x_txt="$HOME/.dotfiles/data/tmux-256color.txt"

main() {
  if [[ -s "$x_txt" ]] ; then
    tic -x "$x_txt"
  else
    echo "WARNING: tmux-256color terminfo not found: $x_txt"
  fi
}

main "$@"

# EOF
