#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  # Ignore if we're not on OSX
  [[ "$OSTYPE" =~ ^darwin ]] || exit 0

  # A lot of these have been stolen from various guides
  # notable guides:
  # - https://github.com/mathiasbynens/dotfiles/blob/master/.osx

  # Expand save panel by default
  defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
  defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

  # Expand print panel by default
  defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
  defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

  # Save to disk (not to iCloud) by default
  defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

  # Automatically quit printer app once the print jobs complete
  defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

  # Disable the “Are you sure you want to open this application?” dialog
  defaults write com.apple.LaunchServices LSQuarantine -bool false

  # Enable Resume system-wide
  defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool true

  # Disable automatic termination of inactive apps
  defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

  # Disable the crash reporter
  defaults write com.apple.CrashReporter DialogType -string "none"

  # Restart automatically if the computer freezes
  sudo systemsetup -setrestartfreeze on

  # Increase window resize speed for Cocoa applications
  defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

  # Disable the sound effects on boot
  sudo nvram SystemAudioVolume=" "

  # Disable local Time Machine snapshots
  sudo tmutil disablelocal

  # Require password for login
  defaults write com.apple.screensaver askForPassword -int 1
  defaults write com.apple.screensaver askForPasswordDelay -int 0

  # Never go into computer sleep mode
  sudo systemsetup -setcomputersleep Off > /dev/null

  # Check for software updates daily, not just once per week
  defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

  # Make sure our screenshots go to some place sane
  mkdir -p "$HOME/Documents/Screenshots"
  defaults write com.apple.screencapture location ~/Documents/Screenshots
  killall SystemUIServer

  # Turn off press-and-hold giving the non-ANSI unicode characters
  defaults write -g ApplePressAndHoldEnabled -bool false
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
