#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  git clone https://github.com/yyuu/pyenv.git            ~/.pyenv

# git clone https://github.com/tokuhirom/plenv.git       ~/.plenv
# git clone https://github.com/tokuhirom/Perl-Build.git  ~/.plenv/plugins/perl-build/

  git clone https://github.com/rbenv/rbenv.git           ~/.rbenv
  git clone https://github.com/rbenv/ruby-build.git      ~/.rbenv/plugins/ruby-build
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
