#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if ! command -v brew &> /dev/null; then echo "Missing dependency: brew" 1>&2; exit 1; fi

brew_install() {
  local app
  app="$1"

  brew install "$app" || exit 1
}

main() {
  for app in "${homebrew_apps[@]}"; do
    brew_install "$app"
  done

  brew cleanup
}

homebrew_apps=(
  aspell --with-all-langs
  awscli
  base64
  bash
  bash-completion
  binutils
  brew-cask-completion
  checkbashisms
  cmake
  colordiff
  coreutils
  csvkit
  curl
  dateutils
  dialog
  diffutils
  direnv
  dos2unix
  enca
  encfs
  exa
  exiftool
  file-formula
  findutils --with-default-names
  flake8
  git
  glances
  gnu-indent --with-default-names
  gnu-sed --with-default-names
  gnu-tar --with-default-names
  gnu-which --with-default-names
  gnupg
  golang
  grc
  grep --with-default-names
  gzip
  hashdeep
  htop
  hub
  imagemagick
  inetutils
  jq
  keychain
  less
  lesspipe
  libnotify
  libqalculate
  lynx
  mailutils
  make
  media-info
  moreutils
  mosh
  mps-youtube
  ncdu
  ncurses
  nmap
  open-completion
  openssh
  openvpn
  pandoc
  pip-completion
  pipenv
  pv
  pwgen
  pyenv
  qrencode
  ranger
  rename
  rsync
  ruby
  ruby-completion
  sendemail
  shellcheck
  sox
  sshfs
  sxiv
  terminal-notifier
  terraform
  terraform-docs
  terraform_landscape
  tig
  tmux
  tor
  torsocks
  tree
  unar
  vim --with-client-server --with-gettext --with-luajit --with-override-system-vi --with-tcl
  vimpager
  w3m
  watch
  weechat --with-aspell --with-curl --with-lua --with-perl --with-python@2 --with-ruby
  wget
  wine
)


main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
