#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

inconsolata_url='https://github.com/powerline/fonts/blob/master/Inconsolata-g/Inconsolata-g%20for%20Powerline.otf?raw=true'
inconsolata_file='Inconsolata-g_for_powerline.otf'
system_fonts_dir='/Library/Fonts/'

main() {
  cd "$TMP" || exit 1
  curl -L -s "$inconsolata_url" > "$inconsolata_file" || exit 1
  cp "$inconsolata_file" "$system_fonts_dir"
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
