#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if ! command -v vim &> /dev/null; then echo "Missing dependency: vim" 1>&2; exit 1; fi

if ! [[ -d "$HOME/.vim/" ]]
 then echo "Directory not found: $HOME/.vim/" 1>&2
 exit 1
fi

if ! [[ -r "$HOME/.vim/autoload/plug.vim" ]]
 then echo "File not found: $HOME/.vim/autoload/plug.vim" 1>&2
 exit 1
fi

main() {
  # Upgrade & update vim-plug
  vim -c "PlugUpgrade" -c "PlugUpdate" || exit 1
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
