  " Use vim defaults in favor of backward-compatibility with vi
set nocompatible

  " Use modelines
set modeline

  " Use strong encryption when invoked with :X or -x
set cryptmethod=blowfish2
  " EOL formats to try when parsing new files with unclear MIMEtypes
set fileformats="unix,dos"
