---
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Truss Pull requests (humans)
    filters: org:trussworks archived:false
             type:pr is:open -is:draft
             -author:app/renovate -author:app/dependabot
  - title: Truss Pull requests (bots)
    filters: org:trussworks archived:false
             type:pr is:open -is:draft
             author:app/renovate author:app/dependabot
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Truss Issues (humans)
    filters: org:trussworks archived:false
             type:issue is:open
             -author:app/renovate -author:app/dependabot
  - title: Truss Issues (bots)
    filters: org:trussworks archived:false
             type:issue is:open
             author:app/renovate author:app/dependabot
             NOT "Dependency Dashboard"
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  refetchIntervalMinutes: 30
keybindings:
  prs: []
repoPaths: {}
pager:
  diff: ''
