# how to do PR approvals: https://github.com/dlvhdr/gh-dash/issues/175#issuecomment-2034686207
---
prSections:
  - title: My PRs
    filters: is:open author:@me
    layout:
      author:
        hidden: true
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
  - title: PRs on my repos
    filters: is:open user:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # wether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths: # configure where to locate repos when checking out PRs
  :owner/:repo: ~/src/github.com/:owner/:repo # template if you always clone github repos in a consistent location
  dlvhdr/*: ~/code/repos/dlvhdr/* # will match dlvhdr/repo-name to ~/code/repos/dlvhdr/repo-name
  dlvhdr/gh-dash: ~/code/gh-dash # will not match wildcard and map to specified path
keybindings: # optional, define custom keybindings - see more info below
theme: # optional, see more info below
pager:
  diff: less # or delta for example
