[settings]

[virtualenvs]
in-project = true
[virtualenvs.options]
system-site-packages = true  # requires poetry >=1.2

[repositories]
[repositories.pypi_test]
url = "https://test.pypi.org/legacy/"

[repositories.pypi]
url = "https://upload.pypi.org/legacy/"
