[settings]

[virtualenvs]
in-project = true
[virtualenvs.options]

[repositories]
[repositories.pypi_test]
url = "https://test.pypi.org/legacy/"

[repositories.pypi]
url = "https://upload.pypi.org/legacy/"
